### ISSUE TITLE
[RC-192] [Bug] Query diff fails for private models

### ISSUE THREAD

**Issue by kokorin** [DataRecce/recce#171]
### Current Behavior

In our project we have configured several model groups. In each group there are private models to enforce scope.
When we try to run diff we get the following error:

> Error: Parsing Error Node model.recce.generated.<ProjectName> attempted to reference node model.<ProjectName>.int_customers, which is not allowed because the referenced node is private to the 'core' group.

### Expected Behavior

Query diff is calculated and displayed

### Steps To Reproduce

[recce_private_model.zip](https://github.com/DataRecce/recce/files/14222376/recce_private_model.zip)

1. Unpack the zip above
2. pip install -r requirements.txt
3. dbt build
4. dbt docs generate
5. dbt build --target-path target-base
6. dbt docs generate --target-path target-base
7. recce server
8. run diff for `select * from {{ ref("private_model") }}`
9. get the error: "Error: Parsing Error Node model.recce.generated.recce_private_model attempted to reference node model.recce_private_model.private_model, which is not allowed because the referenced node is private to the 'my_group' group."

![image](https://uploads.linear.app/934ced25-db7b-45c5-ba31-730290f15f96/7e27e42b-598e-48f2-933e-05d8ca0311e2/6b93436d-c3d0-44a6-b34b-10ce6c1f296b?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzkzNGNlZDI1LWRiN2ItNDVjNS1iYTMxLTczMDI5MGYxNWY5Ni83ZTI3ZTQyYi01OThlLTQ4ZjItOTMzZS0wNWQ4Y2EwMzExZTIvNmI5MzQzNmQtYzNkMC00NGE2LWIzNGItMTBjZTZjMWYyOTZiIiwiaWF0IjoxNzA3ODAzODQ1LCJleHAiOjE3MDc4OTAyNDV9.kdUYCPR0bJwEKiuO6Mxvj0oQsE7nAl80w9GbaFvU7VE)

### Relevant log output

*No response*

### Environment

* recce: 0.6.0
* OS: Win10
* Python: 3.9
* Data Warehouse: Snowflake and sqlite
* dbt: 1.7.0

### Additional Context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [RC-192](https://linear.app/piperider/issue/RC-192/[bug]-query-diff-fails-for-private-models)</sub>

**Comment by clkao** [comment]
@kokorin thanks for reporting the issue that private models can't be referenced directly.

can you try if adding a temporary [restrict-access config in dbt_project.yml](https://docs.getdbt.com/docs/collaborate/govern/model-access#how-do-i-restrict-access-to-models-defined-in-a-package) helps?

```
restrict-access: True  # default is False
```

if so we'll see if there's anything we can do the override this in recce environment.

**Comment by kokorin** [comment]
@clkao I have tried you suggestion and result is the same. To be honest, I was sure it will be the same as `restrict-access: True` makes rules more strict, not less.

I checked recce code and I think that it should be possible to patch DBT manifest in memory before generating queries.

**Comment by clkao** [comment]
(testing the sync thread feature)

**Comment by clkao** [comment]
@kokorin sorry i meant `restrict-access: False`

**Comment by kokorin** [comment]
@clkao I have tried `restrict-access: False` - the same effect, it's default value, so I didn't expect it to work.

**Comment by popcornylu** [comment]
Thanks for your feedback. I will reproduce this today.

**Comment by popcornylu** [comment]
I can reproduce this issue
<img width="1236" alt="image" src="https://github.com/DataRecce/recce/assets/860633/ba9a0cca-ca46-4a1c-b78a-5b3321e2515d">

**Comment by kokorin** [comment]
@clkao  @popcornylu  thank you! I have checked Recce 0.6.1 and the issue is fixed. Thanks again!
