### ISSUE TITLE
[RC-211] [Feature] Allow to exclude some DBT packages from analysis

### ISSUE THREAD

**Issue by kokorin** [DataRecce/recce#179]
### Describe the feature

In our project we use `dbt_project_evaluator` and `elementary` packages.  `dbt_project_evaluator` is enabled for local development and CI. `elementary` is enabled for DEV and PROD.
Instead of building whole project from main branch locally, we **download DBT artifacts from DEV** (it takes too long to run all models). So when we run Recce locally we see `elementary` models red (removed) and `dbt_project_evaluator` models green (added).

It would be very useful if we can exclude both  `dbt_project_evaluator` and `elementary` packages from comparison when running Recce.

<sub>[RC-211](https://linear.app/piperider/issue/RC-211/[feature]-allow-to-exclude-some-dbt-packages-from-analysis)</sub>

**Comment by popcornylu** [comment]
Ideally, just like to graph in dbt docs,  recce can provide a way to filter the nodes by packages.

![image](https://github.com/DataRecce/recce/assets/860633/b718b2ba-72f4-407a-8a72-33acd256a719)
![image](https://github.com/DataRecce/recce/assets/860633/f17ed03d-b26d-409b-b1d0-dc986d8559a0)

**Comment by popcornylu** [comment]
Related to DRC-191

**Comment by wenluzhangg** [comment]
Same Issue as mine - would like to see this enhancement as well..

**Comment by even-wei** [comment]
[https://github.com/DataRecce/jaffle_shop_duckdb/pull/7](https://github.com/DataRecce/jaffle_shop_duckdb/pull/7) example PR
