### ISSUE TITLE
[RC-248] [Bug] Cannot start Recce server from container

### ISSUE THREAD

**Issue by idalbo** [DataRecce/recce#202]
### Current Behavior

I have installed Recce within a container to test it on dbt `jaffle-shop`. When I run `recce server --port 8000 --host 127.0.0.1` the server is up and running:

![image](https://github.com/DataRecce/recce/assets/49947038/e2e5db08-0b9b-473a-9c82-d6038202cd54)

though I can't seem to be able to access it:

![image](https://github.com/DataRecce/recce/assets/49947038/881d0ae9-c815-4012-be5f-143c545448b0)

### Expected Behavior

I would expect to be able to access the server locally on the browser I use.

### Steps To Reproduce

1. go to [this repo](https://github.com/idalbo/dbt_jaffle_docker) and clone it
2. (optional) if you are on windows, start the Linux distro
3. go to the root folder of the project and follow the readme
4. run `make docker-build`
5. run `make docker-start`
6. run `make dbt-shell`
7. within the container, in the dbt project root folder, run `recce server --port 8000 --host 127.0.0.1`
8. try to access the recce server on `localhost:8000` or `127.0.0.1:8000`

### Environment

- recce: 0.6.0
- OS: Windows/WSL2/docker
- Python: 3.9
- Data Warehouse: postgres
- dbt: 1.7.9

<sub>[RC-248](https://linear.app/piperider/issue/RC-248/[bug]-cannot-start-recce-server-from-container)</sub>

**Comment by clkao** [comment]
hey @idalbo, thanks for trying out Recce!

for the container port forwarding to work, try run:
    recce server --port 8000 --host 0.0.0.0

**Comment by idalbo** [comment]
> hey @idalbo, thanks for trying out Recce!
> 
> for the container port forwarding to work, try run: recce server --port 8000 --host 0.0.0.0

hello, thanks for your answer! It seems to be working with `0.0.0.0`, I also tried this before and I could not start the server. That is really great news!
