### ISSUE TITLE
[RC-249] [Feature] Value Diff for models with Composite Primary Key

### ISSUE THREAD

**Issue by kokorin** [DataRecce/recce#203]
### Describe the feature

Recce Value Diff feature allows to select single column for Value Diff. We use models with Composite Primary key, so we can't run Value Diff.

<sub>[RC-249](https://linear.app/piperider/issue/RC-249/[feature]-value-diff-for-models-with-composite-primary-key)</sub>

**Comment by even-wei** [comment]
Hi @kokorin 

Thank you so much for taking the time to submit this feature request. It's great to hear from users who are keen to see our product evolve and improve. 😀

We've actually had this feature in our backlog, but seeing your interest and recognizing its importance, we're bumping up its priority. We will make it possible soon.

**Comment by popcornylu** [comment]
Our current solution relies on the [audit-helper](https://github.com/dbt-labs/dbt-audit-helper) package. Unfortunately, this package supports only single-column primary key.

As a temporary workaround, you can consider the addition of a [surrogate key](https://docs.getdbt.com/terms/surrogate-key) to the model. Looking ahead, we are also exploring the possibility of Recce facilitating the use of this surrogate key transparently.
