### ISSUE TITLE
[RC-250] [Bug] Profile Diff for a model leads to "Division by zero" error if a table is empty

### ISSUE THREAD

**Issue by kokorin** [DataRecce/recce#204]
### Current Behavior

Profile Diff for a model leads to "Division by zero" error if a table is empty

### Expected Behavior

Profile Diff for empty model should give NaN, NULL or N/A result

### Steps To Reproduce

1. Create empty DBT model in main branch
2. Update DBT model to produce some columns in a branch
3. Follow Recce's instructions to run Recce server
4. Run Recce server
5. Find the model in DAG Lineage
6. Click on the model
7. Click Profile Diff

### Environment

- recce:
- OS:
- Python:
- Data Warehouse:
- dbt:

<sub>[RC-250](https://linear.app/piperider/issue/RC-250/[bug]-profile-diff-for-a-model-leads-to-division-by-zero-error-if-a)</sub>

**Comment by even-wei** [comment]
Hi @kokorin 

Thank you for reporting the bug with detailed steps to reproduce it. Our team will fix it soon.

**Comment by kentwelcome** [comment]
The error message will be changed as follows.
![CleanShot 2024-03-05 at 11 57 29@2x](https://github.com/DataRecce/recce/assets/959606/a365d8d4-fa0d-4d64-b746-3154c5efbc43)

If we can't profile the selected model, we will throw a meaningful reason.
