### ISSUE TITLE
[DRC-258] [Bug] Value Diff does not work in Postgres

### ISSUE THREAD

**Issue by neofreex01** [DataRecce/recce#206]
### Current Behavior

Value Diff in Postgres Cannot work. It shows the error message below.

### Expected Behavior

Show the correct value diff result.

### Steps To Reproduce

1. Update logic for a DBT model in feature branch.
2. Follow Recce's instructions to run Recce server
4. Run Recce server
5. Find the model in DAG Lineage
6. Click on the model
7. Pick up primary key of the model
8. Click Value Diff

### Relevant log output

```shell
Error: Database Error subquery in FROM must have an alias LINE 2: SELECT COUNT(*) AS INVALIDS FROM ( ^ HINT: For example, FROM (SELECT ...) [AS] foo.
```

### Environment

- recce: 0.7.0
- Python: 3.11.6
- Data Warehouse: Postgres
- dbt: 1.7.9

<sub>[DRC-258](https://linear.app/piperider/issue/DRC-258/[bug]-value-diff-does-not-work-in-postgres)</sub>

**Comment by popcornylu** [comment]
HI @neofreex01 , thanks for your feedback.


I try to reproduce this issue by [jaffle-shop](https://github.com/dbt-labs/jaffle_shop) on postgres container
```
docker run --name postgres --rm -p 5432:5432 -e POSTGRES_PASSWORD=postgres postgres
```

profiles.yml
```
jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost 
      port: 5432
      user: postgres
      pass: postgres
      dbname: postgres 
      schema: public
```

packages.yml
```
packages:
  - package: dbt-labs/audit_helper
    version: 0.10.0
```
# Install
```
pip install dbt-postgres   recce
```

# Steps
1. `dbt deps && dbt build`
2. `dbt docs generate`
3. `dbt docs generate --target-path target-base`
4. `recce server`
5. Go to lineage and select `customers` model
6. do value diff, pick the `customer_id` as pk

# Result
I can run successfully.
<img width="1390" alt="image" src="https://github.com/DataRecce/recce/assets/860633/35548717-7ed3-4d49-acb1-16e1acfc70d3">
<img width="1778" alt="image" src="https://github.com/DataRecce/recce/assets/860633/e019c252-1236-4042-aef6-b59ec21add94">


Could you please check the query in the `./dbt/logs` and paste the error sql? My sql is 

```
SELECT COUNT(*) AS INVALIDS FROM (

select
    customer_id as unique_field,
    count(*) as n_records

from "postgres"."public"."customers"
where customer_id is not null
group by customer_id
having count(*) > 1
```

**Comment by neofreex01** [comment]
Hi @popcornylu, thank you for the reply. The following is my sql code.

```
SELECT COUNT(*) AS INVALIDS FROM (

select
    user_id as unique_field,
    count(*) as n_records

from "pure"."my_base_schema"."users"
where user_id is not null
group by user_id
having count(*) > 1

)
```

The code seems similar.
Besides, my Postgres version is 14. I guess this might be the issue. In pg14, it's not allowed to select from subqueries without alias.

**Comment by popcornylu** [comment]
Thanks for your information. I can reproduce in postgres:14
![image](https://github.com/DataRecce/recce/assets/860633/b204cbe8-6b36-428e-bf55-09c6d182f376)
![image](https://github.com/DataRecce/recce/assets/860633/53e7e04d-8128-438e-bcb9-a4df2c4e5095)
