### ISSUE TITLE
[DRC-285] table schema are not parsed properly

### ISSUE THREAD

**Issue by wenluzhangg** [DataRecce/recce#221]
### Current Behavior

<img width="498" alt="image" src="https://github.com/DataRecce/recce/assets/125837787/691cd299-9dad-4263-b1c5-eb78e5d878bf">

column names are not parsed 

### Expected Behavior

column names should be correctly parsed and displayed 

### Steps To Reproduce

same steps as documents

### Environment

- recce: 0.8.1
- OS: macOS Sonoma 14.4
- Python:Python 3.10.5
- Data Warehouse: snowflake
- dbt: 1.6.0

<sub>[DRC-285](https://linear.app/piperider/issue/DRC-285/table-schema-are-not-parsed-properly)</sub>

**Comment by popcornylu** [comment]
I can reproduce this issue
<img width="572" alt="image" src="https://github.com/DataRecce/recce/assets/860633/70543e88-c466-43e7-afc8-5a06d88c1cd4">

**Comment by popcornylu** [comment]
Hi @wenluzhangg 

Thanks for your bug report. The latest v0.8.2 has fixed this issue.
