### ISSUE TITLE
[DRC-326] Add dbt artifacts to Recce state to save time for preparing environments

### ISSUE THREAD

**Issue by even-wei** [DataRecce/recce#247]
Currently, Recce state only contains Recce Checks and Recce Runs. Users would need to prepare the environment to checkout the previous work.

To save time from that, we decide to add dbt artifacts to Recce state files, including `manifest.json` from base, `catalog.json` from base, `manifest.json` from current, and `catalog.json` from current.

While launching Recce server, users can use `--review` option to select dbt artifacts stored in the Recce state file.

**Acceptance Criteria:**

- [X] undefined\~\~\~\~\~\~dbt artifacts are included in Recce state files\~\~\~\~\~\~ move to [DRC-332](https://linear.app/piperider/issue/DRC-332/change-the-behavior-of-state-loading)
- [X] Able to use `--review` while launching Recce server

<sub>From [SyncLinear.com](https://synclinear.com) | [DRC-326](https://linear.app/piperider/issue/DRC-326/add-dbt-artifacts-to-recce-state-to-save-time-for-preparing)</sub>

**Comment by popcornylu** [comment]
In the discussion on last Friday, we determine the lineage/schema information is also stored in the state when exporting  in the Web UI

[20240321 --Recce-State-Naming (Figma)](https://www.figma.com/file/8P8qKbvHZ5CA8IY2Xj9c3j/20240321---Recce-State-Naming?type=whiteboard&node-id=1-425&t=PGUPUEq2gYpcvs8n-0)

**Comment by kentwelcome** [comment]
Merged in #237
