### ISSUE TITLE
[DRC-327] Enhance clarity regarding the baseline and current environments

### ISSUE THREAD

**Issue by even-wei** [DataRecce/recce#248]
Currently, it relies on users to know which environments are used. It could easily confuse developer who is working on multiple branches and the reviewer who loads Recce state from somewhere.

2 Scenario:

1. Switching branches
2. Review Recce CI result

**Acceptance Criteria:**

- [ ] User can see the environment information in Recce GUI, including branches, dbt target, timestamp of the last run.

<sub>From [SyncLinear.com](https://synclinear.com) | [DRC-327](https://linear.app/piperider/issue/DRC-327/enhance-clarity-regarding-the-baseline-and-current-environments)</sub>

**Comment by popcornylu** [comment]
There is no branch information in the `manifest.json`, The branch information can only from `git branch --show-current`

So we can only store the current branch information to the state file

**Comment by popcornylu** [comment]
For dbt target information, we can only get the target used by `recce` , but cannot know the target used to generate the manifest. It could mislead the user for some cases.


[https://schemas.getdbt.com/dbt/manifest/v11/index.html#metadata](https://schemas.getdbt.com/dbt/manifest/v11/index.html#metadata)

**Comment by popcornylu** [comment]
Related [figma](https://www.figma.com/file/FjYmAIpcAEkLsS8x0c7m5w/20240336---Recce-State-Expectations?type=whiteboard&node-id=0-1&t=xZK8DZPvzEyRLq7G-0)

**Comment by popcornylu** [comment]
Todos

- [ ] User should know if it is in review mode
- [ ] Which PR he is in
  - [ ] Title, ID, URL, 
- [ ] The base/current branch
- [ ] The catelog/manifest
- [ ] The source file
- [ ] We need to know the PR information.
