### ISSUE TITLE
[DRC-339] [Bug] Schema does not display correctly in Google Chrome

### ISSUE THREAD

**Issue by waligob** [DataRecce/recce#257]
### Current Behavior

In Google Chrome, when selecting a model from the Lineage view, the schema panel just displays the column ordinal. When you navigate to the Schema Check view, the schema also just displays the ordinal until you click "Copy to Clipboard", at which point the column name appears (albeit in an awkward format)

[https://github.com/DataRecce/recce/assets/93673562/277d3bf5-c5e8-47e9-a1d2-d4e04215bdaf](https://github.com/DataRecce/recce/assets/93673562/277d3bf5-c5e8-47e9-a1d2-d4e04215bdaf)

### Expected Behavior

I expect the schema to appear similar to the following (from Firefox):

![image](https://uploads.linear.app/934ced25-db7b-45c5-ba31-730290f15f96/ca7b2e77-cf4d-4a2a-aa6d-d2ddddbbe000/0013d155-54b8-4a2e-a1cc-f8caacda5441?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzkzNGNlZDI1LWRiN2ItNDVjNS1iYTMxLTczMDI5MGYxNWY5Ni9jYTdiMmU3Ny1jZjRkLTRhMmEtYWE2ZC1kMmRkZGRiYmUwMDAvMDAxM2QxNTUtNTRiOC00YTJlLWExY2MtZjhjYWFjZGE1NDQxIiwiaWF0IjoxNzExNjU4Njg4LCJleHAiOjE3MTE3NDUwODh9.nvgF1D11eJmDXk_Ehw5IeiWI46XU9ndjQRwOEaGHytU)

### Steps To Reproduce

1. start Recce server
2. in the Lineage view, select a model, and observe the schema panel
3. Click "Add check" > "Schema check" and note the schema display
4. Click "Copy to clipboard" and note the schema display

### Relevant log output

```shell
N/A [Nothing out of the ordinary in the web server logs]
```

### Environment

* recce: 0.10.0
* OS: linux-gnu
* Python: 3.9.17
* Data Warehouse: BigQuery
* dbt: 1.7.10 (BigQuery plugin 1.7.6)

### Additional Context

*No response*

<sub>From [SyncLinear.com](https://synclinear.com) | [DRC-339](https://linear.app/piperider/issue/DRC-339/[bug]-schema-does-not-display-correctly-in-google-chrome)</sub>

**Comment by popcornylu** [comment]
Hi @waligob 

Thanks for your feedback. I try to reproduce your issue but i cannot reproduce it. Here is my recording.

OS: Mac 14.2.1
Chrome version: (latest) 123.0.6312.87 (arm64)

https://github.com/DataRecce/recce/assets/860633/f3bc0a0a-62c6-4a4f-a9a6-5a14ff6be201

And output screenshot
![image](https://github.com/DataRecce/recce/assets/860633/82fb1280-4487-40cd-8496-04ad11eec5fe)




To facilitate troubleshooting, I would like you to do the following:

- Check if this issue also occurs in the [demo instance](https://pr1.cloud.datarecce.io/)
- Update to the latest version of Chrome to see if the problem still persists.

**Comment by waligob** [comment]
Thanks for the response, @popcornylu. It turns out I was on an old version of Chrome (`Version 95.0.4638.54 (Official Build) (arm64)`). Updating to `Version 123.0.6312.87 (Official Build) (arm64)` resolved the issue. I think this can be closed.

**Comment by clkao** [comment]
thanks @waligob!
