### ISSUE TITLE
[DRC-520] [Bug] Column diff display for VIEW models

### ISSUE THREAD

**Issue by tomoki-takahashi-oisix** [DataRecce/recce#356]
### Current Behavior

I modified two models. Both involved only adding columns, with no change in the number of rows. The first is a TABLE, and the second is a VIEW model that references the first table. In the first model, the added columns are displayed in the Column Diff. However, for the second model, the Column Diff was not displayed. Nevertheless, when viewing other diffs such as the Profile Diff, the added columns were shown as part of the diff

### Expected Behavior

I would like the Column Diff to be correctly displayed even for VIEW models.

### Steps To Reproduce

1. `git switch (prod_branch)`
1. `dbt docs generate --target-path target-base/  -t prod`
2. `git switch (develop_branch)`
3. modify `modes/first.sql` and  `models/second.sql`
4. `dbt run -s first -s second --defer --state target-base --favor-state`
5. `dbt docs generate`
6. `recce server`

### Environment

- recce: 0.22.3
- OS: MacOS 14.4.1
- Python: 3.11.9
- Data Warehouse: snowflake
- dbt: 1.7.1

<sub>[DRC-520](https://linear.app/piperider/issue/DRC-520/[bug]-column-diff-display-for-view-models)</sub>

**Comment by popcornylu** [comment]
HI @tomoki-takahashi-oisix 

Thanks for your feedback, we will try to reproduce it. Will get back to you if there is any finding.

**Comment by popcornylu** [comment]
I cannot reproduce this issue.

## Reproduce steps

Based on the [5-min tutorial](https://datarecce.io/docs/get-started-jaffle-shop/)

Recce version 0.22.3
Warehouse: duckdb

1. provide tables `customers` table model and `customers_view` view model.

    ```
    {{
        config(
            materialized='view'
        )
    }}
    
    select * from {{ ref('customers') }}
    ```
2. Run
    ```
    dbt run --target prod --target-path target-base
   dbt docs generate --target prod --target-path target-base
   ```
2. Modify the `customers`, add new column 

     ```diff
         customers.first_name,
         customers.last_name,
     +   customers.last_name as lastl_name_2,
         customer_orders.first_order,
    ```
3.  Run
    ```
    dbt run -s customers -s customers_view --defer --state target-base --favor-state
    dbt docs generate
    ```
4. Run recce
     ```
     recce server
     ```
     
## Result     
![image](https://github.com/DataRecce/recce/assets/860633/9a23a179-8f8b-402c-a121-c983619632d5)

dbt docs 
![image](https://github.com/DataRecce/recce/assets/860633/a58ad058-28b5-4c97-8e13-2d35a0e98397)

![image](https://github.com/DataRecce/recce/assets/860633/d4b7cfe3-2633-42b6-9141-177f0dfe179d)

**Comment by tomoki-takahashi-oisix** [comment]
Sorry, I forgot to run `dbt docs generate` after running `dbt run`, 
So this issue is closed. Sorry for the investigation.
