### ISSUE TITLE
[DRC-575] [Bug] Advanced Diffs Return Errors in dbt-athena

### ISSUE THREAD

**Issue by tkrishna-equip** [DataRecce/recce#392]
### Current Behavior

All Advanced Diffs run for a long time and return errors 

### Expected Behavior

Advanced Diffs should run quickly and without errors

### Steps To Reproduce

Configure this environment:
dbt core: version 1.6.15
dbt-athena: version 1.6.3
python: 3.9.6

Select Advanced Diffs and try running 

### Environment

- recce: 0.20.0
- OS: MacOS 14.5
- Python: 3.9.6
- Data Warehouse: 
- dbt: 1.6.15

### Additional Context

![image](https://github.com/user-attachments/assets/78953215-9760-40c3-bfe9-5c6a5b3b6627)
![image](https://github.com/user-attachments/assets/727e932e-ded1-436f-8dcc-32ffa2f5c55c)

<sub>[DRC-575](https://linear.app/piperider/issue/DRC-575/[bug]-advanced-diffs-return-errors-in-dbt-athena)</sub>

**Comment by popcornylu** [comment]
For value diff, it seems a issue from audit helper
https://github.com/dbt-labs/dbt-audit-helper/issues/87

Please see the workaround solution a paste in the issue.

**Comment by popcornylu** [comment]
Create a PR in audit-helper
https://github.com/dbt-labs/dbt-audit-helper/pull/108

**Comment by popcornylu** [comment]
Created a PR in dbt-profiler
https://github.com/data-mie/dbt-profiler/pull/91

**Comment by popcornylu** [comment]
The upstreams' PRs aren't merged. I close this issue first, please use the workaround solution mentioned above.
