### ISSUE TITLE
[DRC-663] [Bug] “Error: No profile diff result because the model is empty” when processing BigQuery arrays

### ISSUE THREAD

**Issue by ThiagoTrabach** [DataRecce/recce#415]
### Current Behavior

The Profile Diff feature is not working with tables containing arrays in BigQuery. When calculating the profile diff, an error occurs when it encounters a column with an array: ‘Error: No profile diff result because the model is empty"

### Expected Behavior

Have the Profile Diff calculated for the model.

### Steps To Reproduce

1. Start the Recce server.
2. Select a model that contains a column with an array type.
3. Choose “Profile Diffs.”

### Environment

- recce: 0.32.0
- OS: MacOS 14.6.1
- Python: 3.12.1
- Data Warehouse: BigQuery
- dbt: core=1.8.4, bigquery=1.8.2

### Additional Context

<img width="1297" alt="image" src="https://github.com/user-attachments/assets/8a17c0ce-e26e-4f1c-912e-07b625a343db">

<sub>[DRC-663](https://linear.app/recce/issue/DRC-663/[bug]-error-no-profile-diff-result-because-the-model-is-empty-when)</sub>

**Comment by popcornylu** [comment]
Hi @ThiagoTrabach. Thanks for your feedback. 

Currently, we are using [dbt-profiler](https://hub.getdbt.com/data-mie/dbt_profiler/latest/) results, so its behavior in BigQuery is primarily determined by this package. We will look into the best format for output. In BigQuery, arrays and structs are special data types compared to other warehouses. However, we should be able to output basic information like missing values and distinct counts, and it shouldn’t result in the current output.

**Comment by popcornylu** [comment]
I can reproduce this issue
<img width="1237" alt="image" src="https://github.com/user-attachments/assets/fb8ed29c-ee4a-4d82-9620-6ffd2cb7e71f">

The model I used to reproduce.

```
{{ config(
    materialized='table'
) }}

WITH source_data AS (
    SELECT
        1 AS id,
        'John Doe' AS name,
        ['label1', 'label2', 'label3'] AS labels
    UNION ALL
    SELECT
        2 AS id,
        'Jane Smith' AS name,
        ['labelA', 'labelB'] AS labels
)

SELECT
    id,
    name,
    labels
FROM
    source_data
```

**Comment by popcornylu** [comment]
The profiling issue has been fixed. In addition, we show the array length statistic in the min/max/avg/median column. It makes it easy to observe if there is any change in the array column.

![截圖 2024-09-16 上午9 52 30](https://github.com/user-attachments/assets/85e85c73-edd5-4343-b313-852288d69de1)
