### ISSUE TITLE
[Bug] Python3.8 is not supported by recce

### ISSUE THREAD

**Issue by cedric-orange** [DataRecce/recce#557]
### Current Behavior

I'm want to create a devcontainer features with recce. My devcontainer test fails because it's built with all python version allowed. 
In https://github.com/DataRecce/recce/blob/main/setup.py#L26C4-L26C31 Python 3.8 is allowed, but recce use zoneinfo.

The zoneinfo module was introduced in Python 3.9

### Expected Behavior

Could you update project configuration to remove python 3.8 support ?

### Steps To Reproduce

```bash
podman run -it --rm --entrypoint /bin/bash docker.io/python:3.8
> pip install pipx
> pipx install recce
> recce version
bash: recce: command not found
root@8b8e390c3181:/# root/.local/bin/recce version
Traceback (most recent call last):
  File "root/.local/bin/recce", line 5, in <module>
    from recce.cli import cli
  File "/root/.local/share/pipx/venvs/recce/lib/python3.8/site-packages/recce/cli.py", line 9, in <module>
    from recce import event
  File "/root/.local/share/pipx/venvs/recce/lib/python3.8/site-packages/recce/event/__init__.py", line 14, in <module>
    from recce.event.collector import Collector
  File "/root/.local/share/pipx/venvs/recce/lib/python3.8/site-packages/recce/event/collector.py", line 9, in <module>
    from zoneinfo import ZoneInfo
ModuleNotFoundError: No module named 'zoneinfo'
``

### Relevant log output

_No response_

### Environment

- recce:
- OS:
- Python:
- Data Warehouse:
- dbt:


### Additional Context

_No response_

**Comment by even-wei** [comment]
Hi @cedric-orange 

Thanks for reporting the issue!

We replaced the `zoneinfo` package with `datetime.timezone` and removed python 3.8 support since it's EOL.

Please verify if it works for you with the next next release. 🙌🏼
